#!/bin/zsh

# Make sure you run this terrible script from this folder

DIR=`pwd`
cd ~

# Override current config with links to here
ln -ish "$DIR/.zshrc"        ~/.zshrc
ln -ish "$DIR/.zsh.prompt"   ~/.zsh.prompt
ln -ish "$DIR/.gitconfig"    ~/.gitconfig
ln -ish "$DIR/.gitignore"    ~/.gitignore
ln -ish "$DIR/.vimrc"        ~/.vimrc

# Create override files
touch .gitconfig.local
touch .zshrc.local

# Append local kitty config to existing config
mkdir -p .config/kitty
touch .config/kitty/kitty.conf
if ! grep -q "include $DIR/kitty.conf" .config/kitty/kitty.conf; then
	echo "\ninclude $DIR/kitty.conf" >> .config/kitty/kitty.conf
fi

# Silences last login message
touch .hushlogin

cd $DIR
